//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nasa.pds.registry.common.connection.config;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.pds.registry.common.connection.config package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.pds.registry.common.connection.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistryConnection }
     * 
     * @return
     *     the new instance of {@link RegistryConnection }
     */
    public RegistryConnection createRegistryConnection() {
        return new RegistryConnection();
    }

    /**
     * Create an instance of {@link CognitoType }
     * 
     * @return
     *     the new instance of {@link CognitoType }
     */
    public CognitoType createCognitoType() {
        return new CognitoType();
    }

    /**
     * Create an instance of {@link Ec2Type }
     * 
     * @return
     *     the new instance of {@link Ec2Type }
     */
    public Ec2Type createEc2Type() {
        return new Ec2Type();
    }

    /**
     * Create an instance of {@link DirectType }
     * 
     * @return
     *     the new instance of {@link DirectType }
     */
    public DirectType createDirectType() {
        return new DirectType();
    }

}
