//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nasa.pds.registry.common.connection.config;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *           This terrible construct is so that xjc can autodetect this as the
 *           root node for processing. Many things would be better but this is
 *           the most workable solution especially if the making of the binding
 *           code is automated in the pom. The only other real solution is to
 *           modify one of the classes generated by hand.
 *         
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="cognitoClientId" type="{}cognito_type"/>
 *         <element name="ec2_credential_socket" type="{}ec2_type"/>
 *         <element name="server_url" type="{}direct_type"/>
 *       </choice>
 *       <attribute name="index" type="{http://www.w3.org/2001/XMLSchema}normalizedString" default="registry" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cognitoClientId",
    "ec2CredentialSocket",
    "serverUrl"
})
@XmlRootElement(name = "registry_connection")
public class RegistryConnection {

    protected CognitoType cognitoClientId;
    @XmlElement(name = "ec2_credential_socket")
    protected Ec2Type ec2CredentialSocket;
    @XmlElement(name = "server_url")
    protected DirectType serverUrl;
    @XmlAttribute(name = "index")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String index;

    /**
     * Gets the value of the cognitoClientId property.
     * 
     * @return
     *     possible object is
     *     {@link CognitoType }
     *     
     */
    public CognitoType getCognitoClientId() {
        return cognitoClientId;
    }

    /**
     * Sets the value of the cognitoClientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CognitoType }
     *     
     */
    public void setCognitoClientId(CognitoType value) {
        this.cognitoClientId = value;
    }

    /**
     * Gets the value of the ec2CredentialSocket property.
     * 
     * @return
     *     possible object is
     *     {@link Ec2Type }
     *     
     */
    public Ec2Type getEc2CredentialSocket() {
        return ec2CredentialSocket;
    }

    /**
     * Sets the value of the ec2CredentialSocket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ec2Type }
     *     
     */
    public void setEc2CredentialSocket(Ec2Type value) {
        this.ec2CredentialSocket = value;
    }

    /**
     * Gets the value of the serverUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DirectType }
     *     
     */
    public DirectType getServerUrl() {
        return serverUrl;
    }

    /**
     * Sets the value of the serverUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectType }
     *     
     */
    public void setServerUrl(DirectType value) {
        this.serverUrl = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        if (index == null) {
            return "registry";
        } else {
            return index;
        }
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

}
