package gov.nasa.pds.registry.common.mq.msg;

/**
 * A message to harvest collection inventory
 * @author karpenko
 */
public class CollectionInventoryMessage
{
    /**
     * Harvest job ID. Autogenerated UUID.
     */
    public String jobId;
    
    /**
     * Collection lidvid
     */
    public String collectionLidvid;
    
    /**
     * Inventory file path
     */
    public String inventoryFile;

    /**
     * Overwrite existing products in the Registry (Elasticsearch) if set to true.
     */
    public boolean overwrite = false;
}
