package gov.nasa.pds.registry.common.mq.msg;

import java.util.List;
import java.util.Set;

/**
 * A message to crawl a directory.
 * @author karpenko
 */
public class DirectoryMessage
{
    /**
     * Harvest job ID. Autogenerated UUID.
     */
    public String jobId;
    
    /**
     * PDS node name, such as "PDS_ENG".
     */
    public String nodeName;

    /**
     * Directory (full path) to crawl
     */
    public String dir;
    
    /**
     * Manifest file (contains list of files to process)
     */
    public String manifest;
    
    /**
     * Product class filter. List of classes to include.
     */
    public Set<String> prodClassInclude;
    
    /**
     * Product class filter. List of classes to exclude.
     */
    public Set<String> prodClassExclude;
    
    /**
     * List of rules to generate file references.
     */
    public List<String> fileRefs;

    /**
     * Overwrite existing products in the Registry (Elasticsearch) if set to true.
     */
    public boolean overwrite = false;

    
    /**
     * Constructor
     */
    public DirectoryMessage()
    {
    }
}
